name: run-eslint
on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - run: npm install
      working-directory: ./frontend
    - run: npx eslint .
      working-directory: ./frontend
