name: run-eslint
on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
          with:
            node-version: 'lts/*'
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend
      - name: Run eslint
        working-directory: ./frontend
        run: npx eslint .
